#!/bin/bash
# Helper scripts for running Docker with Doppler

echo "🚀 EV Rental System Backend - Docker + Doppler Helper"
echo ""
echo "Available commands:"
echo ""
echo "Development:"
echo "  npm run docker:dev     - Build and run development environment"
echo "  npm run docker:dev:bg  - Build and run development environment in background"
echo ""
echo "Staging:"
echo "  npm run docker:stg     - Build and run staging environment"
echo "  npm run docker:stg:bg  - Build and run staging environment in background"
echo ""
echo "Production:"
echo "  npm run docker:prd     - Build and run production environment"
echo "  npm run docker:prd:bg  - Build and run production environment in background"
echo ""
echo "Manual usage:"
echo "  doppler run -- docker compose -f compose.dev.yaml up --build"
echo "  doppler run --config stg -- docker compose -f compose.staging.yaml up --build"
echo "  doppler run --config prd -- docker compose -f compose.production.yaml up --build"
echo ""